### ISSUE TITLE
Auto-resizing input buffer

### ISSUE THREAD

**Issue by Willy-JL** [pyimgui/pyimgui#278] opened 2022-04-21 23:34 UTC
I wanted my end user to be able to input as much text as they want, but setting a high `bugger_length` causes of course more CPU usage, so I'd have to find a compromise...

I saw this mentioned in upstream [here](https://github.com/ocornut/imgui/issues/2006#issuecomment-415001689) with this example from Omar himself:
```cpp
static int InputTextCallback(ImGuiInputTextCallbackData* data)
{
    if (data->EventFlag == ImGuiInputTextFlags_CallbackResize)
    {
        // Resize string callback
        std::string* str = (std::string*)data->UserData;
        IM_ASSERT(data->Buf == str->c_str());
        str->resize(data->BufTextLen);
        data->Buf = (char*)str->c_str();
    }
}

bool ImGui::InputText(const char* label, std::string* str, ImGuiInputTextFlags flags)
{
    flags |= ImGuiInputTextFlags_CallbackResize;
    return InputText(label, (char*)str->c_str(), str->capacity() + 1, flags, InputTextCallback, (void*)str);
}
```

I saw that callbacks were implemented in pyimgui and so I tried to recreate it:
```py
buf = ""
buf_size = 1

def resize_buf(data):
    global buf_size
    buf_size = buffer_text_length

# ...
while True:
    # ...
    _, buf = imgui.input_text("test", buf, buf_size, flags=imgui.INPUT_TEXT_CALLBACK_RESIZE, callback=resize_buf)
    # ...
````
And it works well, until it doesn't... I can insert up to 20~40 characters and then it crashes, and it has a different message nearly each time, here are some I've seen:
```
corrupted size vs. prev_size
free(): invalid pointer
free(): invalid next size (fast)
python: malloc.c:4302: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.

all of these were followed by a:
zsh: IOT instruction (core dumped)  /home/willyjl/.pyenv/versions/3.10.0/bin/python


also sometimes i  get a segfault with no prior error message:
zsh: segmentation fault (core dumped)  /home/willyjl/.pyenv/versions/3.10.0/bin/python
```
I also tried adding 1, 10, 100 and so on  to the buffer size when resizing, or even multiplying it, nothing. Am I doing something  wrong?

I am on Garuda Linux, kernel 5.15.34 lts, on dev/version-2.0 branch built locally of course, python 3.10.0

**Comment by KinoxKlark** [comment] 2022-04-24 08:02
Mmh, it's a nasty one... It raises issues with the current implementation that won't be easy to fix. I have played a bit with it and as far as I can tell the problem is the following:

1. You call `input_text()` with a given buffer_size
2. Internally, we allocate memory for a buffer of `buffer_size*sizeof(char)` chars. (Which may not corresponds to the number of characters depending on the text format, e.g. utf-8 may use more than 1bit per character, this may be misleading for python users)
3. We copy the user python buffer to the new buffer
4. We call the dearimgui implementation of `InputText`
5. Callback occurs when the text that has to be inserted is longer than the allocated buffer. (It may be multiple `char` longer if the user tapes multiple letters during the frame or if it copy/past some text)
6. In your callback function you set the `buffer_size` for the next frame but the internal buffer still has its original size which leads to crash

To solve the problem one would want to resize the internal buffer in the callback. Unfortunately, the current interface does not allow to manipulate it at all (it is never passed through, even if you use `user_data`), and it is unclear to me how one would do that in python...

We could easily bake the feature inside `pyimgui` directly... It may be the only option here. I have to think a bit about that because this shows that the input callback mechanic may have to be refactored a bit to allow data manipulation.

**Comment by Willy-JL** [comment] 2022-04-24 10:52
Thanks for looking into it.

Yeah I had a hunch this wouldn't be easy given how different characters are handled between C++ and Python. I think that baking it directly into pyimgui would also be very beneficial to the average user, because as a Python user you're not accustomed to managing or working around buffer sizes. Perhaps this could be set with a custom `bool resize` flag, or even easier just setting the buffer size to 0 or negative? Either way I'd love to implement this myself but it's fare beyond my capabilities :/

**Comment by KinoxKlark** [comment] 2022-04-24 13:34
Ok so, it was such a rabbit hole ^^
I figured out a way to edit the buffer from the callback. I still have a strange crash when I try to correctly free the allocated memory, but I have to take a break before finishing and propose a fix.

**Comment by Willy-JL** [comment] 2022-06-05 16:28
Any news? :D

**Comment by KinoxKlark** [comment] 2022-06-05 17:01
Hey sorry! Unfortunately I am overloaded with work these recent days and I couldn't find time to advance on that. I probably won't have any time until mid-July.

**Comment by KinoxKlark** [comment] 2022-08-07 17:45
Hey, I finally could take some time to work on it. I have proposed a fix in #291

Finally, I choose to implement it internally to `pyimgui` since this is the only place where the memory is managed, and this is invisible to python users. I also simplified the interface a bit to be more python friendly. One can now omit the `buffer_length` argument, which would automatically use the resizing functionality leading to simpler code:
```python
_, buf = imgui.input_text("Basic", buf)
_, buf = imgui.input_text_multiline("Multiline", buf)
_, buf = imgui.input_text_with_hint("With hint", "astuce", buf)
```

More details on the PR, what do you think of this solution?

**Comment by Willy-JL** [comment] 2022-08-07 18:11
Looks perfect to me, great job!

**Comment by KinoxKlark** [comment] 2022-08-10 08:46
I merged the fix to `dev/version-2.0`, thus I will close this issue. Let me know if I have missed anything.

**Comment by Willy-JL** [comment] 2022-08-11 17:43
I feel bad bearing mediocre news after all the effort you put into this brilliant fix, but I've got a small bug report.

Backspaces now count as null bytes, so inputting text is fine but when you go to delete some characters the output on python side is polluted with \x00 chars. I was having some very weird behavior in my interface and couldn't figure it out until I tried printing the repr() of the input_text() return value, and lo and behold \x00 fest xD. I'm guessing this slipped under the radar also because of that, simple debug prints and average usage wouldn't catch this type of thing.

**Comment by KinoxKlark** [comment] 2022-08-12 06:28
Thanks for letting me know. I'll look into it as soon as possible!

**Comment by KinoxKlark** [comment] 2022-08-12 10:17
It should be now fixed by https://github.com/pyimgui/pyimgui/commit/84bc6bcb9248fc3eb858ee59f144ee067e13ec24. Please forgives me for the mistake. Let me know if there is anything else!

**Comment by Willy-JL** [comment] 2022-08-12 18:08
Can confirm it's fixed, thanks for the quick response!

**Closed** 2022-08-12 18:08 UTC
