### ISSUE TITLE
Adding an initial position to a window

### ISSUE THREAD

**Issue by TechStudent10** [pyimgui/pyimgui#290] opened 2022-08-06 22:56 UTC
How do I add an initial position to a window? And how do I disable the `imgui.ini` file? I am using the Pygame Integration.

**Comment by KinoxKlark** [comment] 2022-08-07 18:03
The initial position of the window depends on pygame, not on pyimgui, so I cannot help you with that.

For the `imgui.ini` file, it should be doable with
```python
io = imgui.get_io()
io.ini_file_name = 'other_name.ini'
```
or even for disabling it totally and managing manually with `load_ini_settings_from_disk()`, `load_ini_settings_from_memory()`, `save_ini_settings_to_disk()`, `save_ini_settings_to_memory()`, you could do
```python
io.ini_file_name = None
```

However, as I test it now, it doesn't work and leads to a crash. This is clearly a bug, and I will try to fix it as soon as possible.

**Comment by learn-more** [comment] 2022-08-08 07:49
> However, as I test it now, it doesn't work and leads to a crash. This is clearly a bug, and I will try to fix it as soon as possible.

This might be caused by #232

**Comment by KinoxKlark** [comment] 2022-08-08 09:13
Indeed it works properly when using directly bytes, e.g.
```python
io.ini_file_name = b'other_name.ini' # set another name
io.ini_file_name = b'' # disable ini file
```

But I think it is a bit unnatural for python users to have to pass by those. Wouldn't it be more natural to use strings directly?
```python
io.ini_file_name = "other_name.ini" # set another name
io.ini_file_name = None # disable ini file
```

**Comment by KinoxKlark** [comment] 2022-08-08 12:19
This has been fixed in #292, I merged it in `dev/version-2.0`. 

I close the issue since it has been answered; feel free to reopen it if you think there is something more.

**Closed by KinoxKlark** 2022-08-08 12:19 UTC
Labels: bug

**Comment by TechStudent10** [comment] 2022-08-08 17:10
> The initial position of the window depends on pygame, not on pyimgui, so I cannot help you with that.

Hm okay. I don't think that answers the question. Does that mean that I have to do some Pygame tricks and hacks in order to set where to spawn the window, or is it just totally impossible to do so?

**Comment by KinoxKlark** [comment] 2022-08-08 17:50
What I meant is that `pyimgui` is only responsible for the drawing of graphical elements, not the management of the window. Window management (such as position, size, fullscreen, and so on) is done by the backend you choose (here Pygame, but it could be glfw or any other). So in order to set the position of the window, you should look at how this is done via Pygame.

But maybe I misunderstood the question, and I am sorry for that. If by "window" you meant the element drawn by `pyimgui` via the `begin()`/`end()` command (which is a small window inside the actual window of your program) you can manage its position and size via `set_next_window_position()` and `set_next_window_size()`. Which would be used before calling to `begin()`, e.g.
```python
imgui.set_next_window_size(20, 20) # width, height
imgui.set_next_window_position(40, 5) # x, y
imgui.begin(str(index))
# ...
imgui.end()
```
I hope this will help you.

**Comment by TechStudent10** [comment] 2022-08-08 17:51
Ah yes that is what I was looking for. Maybe I should've been a bit more specific. Thanks!
