### ISSUE TITLE
imgui.text() render icons from ttf font

### ISSUE THREAD

**Issue by tycheng** [pyimgui/pyimgui#149] opened 2020-05-13 04:15 UTC
Hi, when I tried to use some custom ttf icon font, I could only render digits + alphabets.
Any icon I use from the font does not render at all (only shows up as empty).

I am trying to use the unicode of the icon in the following form.

`imgui.text('\uf018')`

Does pyimgui support rendering icons like this?
What is the expected way to render icons?
Thank you.

![image](https://user-images.githubusercontent.com/5659358/81770590-6351ab00-94a6-11ea-9612-d052a36852c7.png)

**Comment by totomobile43** [comment] 2020-06-15 21:48
Hey, so I also ran into this issue. The cause is that 
`io.fonts.add_font_from_file_ttf(os.path.join('Custom.ttf'), 32)`
will just load the default unicode range (a-z and some numbers).

You can also ask it to load additional character sets, e.g. :
`io.fonts.add_font_from_file_ttf(os.path.join('Custom.ttf'), 32, io.fonts.get_glyph_ranges_chinese())`

As you write above, you can directly address characters by their unicode id. However, if load something like an icon font, then its glyphs are stored in some random unicode range that is *not* loaded by pyimgui. For example, in Google Material Design Icons, the glyphs are stored in the range e000 -> fffd. 

Currently pyimgui only accepts from a number of predefined ranges, so if you want to use an icon font, you will have to manually move the glyphs to unicode ranges that are loaded. You can do this using something like FontForge (free).

However, the best solution is if pyimgui allows for loading custom ranges (which is trivial in the c++ version that allows you to set the pointer directly). This could be done with a new wrapper python function that converts some numerical range to the expected pointer.

Hope this helps, and looking forward to future versions of pyimgui :)

**Comment by totomobile43** [comment] 2020-06-16 10:22
Along the same lines, another use case that is not supported is merging glyphs into the default font. It would be great to support this as well!

**Comment by Johndeep** [comment] 2021-03-02 16:26
By the way, since it is very often used in the "mainline" projects (aka projects written directly in C++), can I assume that including Icon fonts like "Font Awesome" will not work currently? (Not until the PR v1.81 at least?)

It seems that the range for calling "add_font_from_file_ttf" is of a strange type "_StaticGlyphRanges", so that I don't know how to set any range at all.. if possible, I would just expect something like a simple list or tuple. At least to be able to manually set a certain range if one know exactly the range.

**Comment by saulthu** [comment] 2021-10-21 04:44
This would be better if the codepoint range defaulted to 32-bit within the C++ build. It would be nice to be able to construct an arbitrary font configs and glyph ranges as noted in #35, and ideally would not need to construct a texture with *all* of the glyphs, rather just the few we use e.g. [MDI](https://github.com/Templarian/MaterialDesign-Webfont) currently has > 6000 glyphs so the code above results in a 4096x4096 texture for this font.

**Comment by saulthu** [comment] 2021-10-21 23:50
And it works for _any_ font, not just the one that I chose to work with 😄

**Comment by KinoxKlark** [comment] 2022-01-30 08:54
This should be fixed thanks to @saulthu in #241. I merged the fix in branch `dev/version-2.0`. Let me know if there is any problem.

**Closed by KinoxKlark** 2022-01-30 08:54 UTC
Labels: enhancement / feature, question / hint, todo
